<!doctype html><html lang="zh-CN" data-theme="light" data-scheme="pine"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Icimik Composer · Design system</title><style>
{{slot0}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:var(--base) var(--ui)}button,select,textarea{font:inherit;color:inherit}button,select{background:var(--surface);border:1px solid var(--control-line);padding:var(--s2) var(--s3);border-radius:var(--radius);min-height:var(--target);cursor:pointer}button:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:2px solid var(--accent);outline-offset:var(--s1)}a{color:var(--accent)}header,main{padding:var(--s6);max-width:calc(var(--measure) * 2);margin:auto}header{display:flex;gap:var(--s4);align-items:center;flex-wrap:wrap;border-bottom:1px solid var(--line)}h1{font-size:var(--title);font-weight:500;margin:0}h2{font-size:var(--lg);font-weight:600}p{line-height:1.9}nav{display:flex;gap:var(--s4);flex-wrap:wrap}section{margin-bottom:var(--s10)}.controls{margin-left:auto;display:flex;gap:var(--s3);flex-wrap:wrap}.scene{border:1px solid var(--control-line);border-radius:var(--radius);overflow:hidden;background:var(--surface)}.scene-head{display:flex;justify-content:space-between;align-items:center;gap:var(--s3);padding:var(--s4);border-bottom:1px solid var(--line)}.scene-grid{display:grid;grid-template-columns:var(--sidebar-width) minmax(0,1fr) var(--ai-width)}.tree{background:var(--sidebar);padding:var(--s5);border-right:1px solid var(--line)}.tree button{display:block;width:100%;text-align:left;margin-bottom:var(--s2)}.tree p{color:var(--muted);font-size:var(--xs)}.prose{padding:var(--s8);font-family:var(--prose)}.prose textarea{width:100%;min-height:calc(var(--s12)*4);border:0;background:transparent;font:var(--prose-size)/2.1 var(--prose);resize:vertical}.prose h3{font-size:var(--title);font-weight:400}.assistant{padding:var(--s5);border-left:1px solid var(--line)}.primary{background:var(--accent);color:var(--on-accent)}.card{padding:var(--s5);border:1px solid var(--control-line);border-radius:var(--radius);background:var(--surface)}.muted{color:var(--muted);font-size:var(--sm)}.states{display:grid;grid-template-columns:repeat(auto-fit,minmax(var(--sidebar-width),1fr));gap:var(--s4)}.error{color:var(--danger);background:var(--danger-bg);padding:var(--s4)}.success{color:var(--accent);background:var(--selected);padding:var(--s4)}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:var(--xs)}td,th{padding:var(--s2);border-bottom:1px solid var(--line);text-align:left;overflow-wrap:anywhere}.tokens{font-family:var(--mono)}.compact{--s5:16px;--s8:24px}.status{font-size:var(--xs);color:var(--muted)}@media(max-width:940px){.scene-grid{grid-template-columns:minmax(0,1fr)}.tree,.assistant{border:0;border-bottom:1px solid var(--line)}.controls{margin-left:0}.prose{padding:var(--s5)}}@media(prefers-reduced-motion:reduce){*{transition:none}}@media(forced-colors:active){button,select{border-color:ButtonText}.primary{background:ButtonFace;color:ButtonText}}
</style></head><body><header><svg width="26" height="26" viewBox="0 0 26 26" aria-label="Composer 标志"><path d="M5 4h7v17H5zM14 4h7v17h-7z" fill="none" stroke="currentColor"/></svg><h1>Icimik Composer · 设计系统</h1><div class="controls"><label>方案 <select id="scheme"><option value="pine">松墨</option><option value="mono">石墨</option></select></label><label>明暗 <select id="mode"><option value="light">明</option><option value="dark">暗</option></select></label><label>密度 <select id="density"><option value="comfortable">舒适</option><option value="compact">紧凑</option></select></label></div></header><main><nav id="toc" aria-label="章节目录"></nav>
<section id="writing"><h2>完整场景 · 写作与提案</h2><p class="muted">设计场景，不调用 AI、不保存文稿；可体验编辑、选择与提案裁决。</p><div class="scene"><div class="scene-head"><strong>雾港来信 / 样章创作</strong><span class="status" id="save-status">已保存（展示）</span></div><div class="scene-grid"><aside class="tree"><p>作品资料</p><button id="chapter">第一章 · 迟来的信</button><button id="character">人物 · 林遥</button><p>会话共享唯一正文，提案独立保留。</p></aside><div class="prose"><h3 id="title">第一章 · 迟来的信</h3><textarea id="manuscript" aria-label="展示正文">雨停在凌晨四点。

林遥推开邮局的门。柜台后的老人没抬头，只把一封信推到灯下。

“你的。”</textarea></div><aside class="assistant"><h2>创作助手</h2><p class="muted">当前章 + 指令 + 所选设定 + 中文约束</p><div class="card"><p id="proposal">信封上的名字是她的。邮戳却是二十年前。</p><button id="discard">放弃</button> <button class="primary" id="accept">采纳</button></div><p class="status" id="decision" role="status">提案尚未写入正文。</p></aside></div></div></section>
<section id="states"><h2>交互状态</h2><div class="states"><div class="card"><h3>空状态</h3><p class="muted">还没有提案。先描述这一章的任务。</p><button id="reset">重置场景</button></div><div class="card"><h3>生成中</h3><p class="muted" id="generation">正在等待模型（展示）</p><button id="cancel">取消生成</button></div><div class="card"><h3>错误与恢复</h3><p class="error" role="alert">正文已变化，不能采纳旧提案。请基于新正文重新生成。</p><p class="success">已恢复快照，恢复前的正文也已保留。</p></div><div class="card"><h3>焦点与禁用</h3><p class="muted">用 Tab 检查焦点。状态总有文字，不只靠颜色。</p><button disabled>正在保存</button></div></div></section>
<section id="contrast"><h2>实时对比度</h2><p class="muted">当前方案／明暗：<span id="active-mode"></span>。普通文本 ≥ 4.5，有意义边界 ≥ 3；装饰分隔线不作交互边界。</p><div class="table-wrap"><table><thead><tr><th>前景</th><th>背景</th><th>比值</th><th>阈值</th><th>结果</th></tr></thead><tbody id="contrast-body"></tbody></table></div></section>
<section id="tokens"><h2>完整 token 表</h2><div class="table-wrap"><table class="tokens"><thead><tr><th>名称</th><th>当前值</th></tr></thead><tbody id="tokens-body"></tbody></table></div></section>
<section id="boundary"><h2>表面边界与验证</h2><p>此页面只控制创作工作台的视觉语言，不改变 OS 弹窗、终端、未来 IF 播放器或印刷稿。所有字体离线回退；无 CDN、无构建步骤、无外部资源。</p><p>规范与展示由同一 CSS token 源生成。design:check 对四个方案／明暗组合计算配对，解析规范和展示并检测漂移，故意改色的反例必须失败。</p></section></main>
<script id="design-tokens" type="application/json">{{slot1}}</script><script>
{{runtime}}
createShowcase({pairs:{{slot2}},luminance:{{slot3}}});
</script></body></html>